version: "3.2"

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  nginx:
    image: nginx
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/www.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    ports:
      - 80:80
  postgres:
    build:
      context: ./docker/postgres
    ports:
      - "9003:5432"
    environment:
      - POSTGRES_USER=internet_crawler
      - POSTGRES_PASSWORD=internet_crawler
      - POSTGRES_DB=internet_crawler
    volumes:
      - postgres_data:/var/lib/postgresql/data
  horizon:
    build: ./docker/php
    command: /usr/bin/env php artisan horizon
    volumes:
      - .:/var/www/html
  redis:
    image: redis
volumes:
  postgres_data:
    driver: "local"
